[ubuntu_lab]
ubuntu ansible_host=127.0.0.1 ansible_port=2201

[fedora_lab]
fedora ansible_host=127.0.0.1 ansible_port=2202

[debian_lab]
debian ansible_host=127.0.0.1 ansible_port=2203

[archlinux_lab]
archlinux ansible_host=127.0.0.1 ansible_port=2204

[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=./keys/id_ansible
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
